# Generated by Django 6.0.2 on 2026-04-06 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enforce_single_admin(apps, schema_editor):
    Perfil = apps.get_model("core", "Perfil")
    admin_profiles = list(Perfil.objects.filter(rol="admin").order_by("id"))

    if len(admin_profiles) <= 1:
        return

    for perfil in admin_profiles[1:]:
        perfil.rol = "recepcionista"
        perfil.save(update_fields=["rol"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_rol_normalize_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('resource_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(enforce_single_admin, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'admin')), fields=('rol',), name='unique_admin_role'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
